### ISSUE TITLE
(No issue) Thanks for sharing – we need every AzuraCast Plugin example we can get …

### ISSUE THREAD

**Issue by Moonbase59** [RM-FM/AzuraCastPlugin-LSConfigReplace#1]
You don’t have "Discussions" open on this repo, so I’m mis-using the issues, sorry.

Thanks for sharing a nice and useful example for using the AzuraCast plugin architecture. We definitely need more plugin examples like this, so I’d be grateful if you’d keep this public—thanks!

I was actually thinking of modifying the Liquidsoap code for my stations myself, but had no good idea for not breaking compatibility. This is a well thought-out example. Kudos.

_Note:_ You might want to move the `ls-config-replace` folder up a level (so `events.php` is in the root folder). This would ease git cloning:

```bash
cd /var/azuracast/plugins
git clone https://github.com/RM-FM/AzuraCastPlugin-LSConfigReplace.git
```

and we would get a `plugins/ls-config-replace` subfolder that has `.git` and `.gitignore` in the subfolder. As it is now, we’d either mess up other git clones if cloning into the plugins folder, or have to shift things around before use.

Should you decide to do that, it’d of course also make sense to rename the repo?

**Comment by RM-FM** [comment]
@Moonbase59 Thank you for the positive feedback! Disussion is open now 👍🏼

**Comment by RM-FM** [comment]
> _Note:_ You might want to move the `ls-config-replace` folder up a level (so `events.php` is in the root folder). This would ease git cloning:
> 
> ```shell
> cd /var/azuracast/plugins
> git clone https://github.com/RM-FM/AzuraCastPlugin-LSConfigReplace.git
> ```
> 
> and we would get a `plugins/ls-config-replace` subfolder that has `.git` and `.gitignore` in the subfolder. As it is now, we’d either mess up other git clones if cloning into the plugins folder, or have to shift things around before use.
> 
> Should you decide to do that, it’d of course also make sense to rename the repo?

@Moonbase59 There you go... :-)
